import {
    agonda2,
    agonda1,
    agonda3,
    alibaug1,
    alibaug2,
    alibaug3,
    bhimtal1,
    bhimtal2,
    bhimtal3,
    canacona1,
    canacona2,
    canacona3,
    dapoli1,
    dapoli2,
    dapoli3,
    goa1,
    goa2,
    goa3,
    lonavala1,
    lonavala2,
    lonavala3,
    maldives1,
    maldives2,
    maldives3,
    mandrem1,
    mandrem2,
    mandrem3,
    marchula1,
    marchula2,
    marchula3,
    morjim1,
    morjim2,
    morjim3,
    mumbai1,
    mumbai2,
    mumbai3,
    nagaon1,
    nagaon2,
    nagaon3,
    nainital1,
    nainital2,
    nainital3,
    ramnagar1,
    ramnagar2,
    ramnagar3,
    vagator1,
    vagator2,
    vagator3,
} from './Imgs.js'

let rooms = [
    {
      place: 'Agonda,India',
      img1 : agonda1,
      img2 : agonda2,
      img3 : agonda3,
      host : 'Jeevan',
      price: '8,559',
      date: '1-6',
      rating: '4.64'
    },
    {
      place: 'Alibagh,India',
      img1 : alibaug1,
      img2 : alibaug2,
      img3 : alibaug3,
      host : 'Rishya',
      price: '6,733',
      date: '10-16',
      rating: '4.4'
    },
    {
      place: 'Bhimtal,India',
      img1 : bhimtal1,
      img2 : bhimtal2,
      img3 : bhimtal3,
      host : 'Dinesh',
      price: '3,634',
      date: '2-8',
      rating: '4.84'
    },
    {
      place: 'Canacona,India',
      img1 : canacona1,
      img2 : canacona2,
      img3 : canacona3,
      host : 'Ishan',
      price: '8,559',
      date: '1-6',
      rating: '4.64'
    },
    {
      place: 'Dapoli,India',
      img1 : dapoli1,
      img2 : dapoli2,
      img3 : dapoli3,
      host : 'Arvind',
      price: '4,560',
      date: '5-12',
      rating: '4.83'
    },
    {
      place: 'Goa,India',
      img1 : goa1,
      img2 : goa2,
      img3 : goa3,
      host : 'Nikhil',
      price: '10,156',
      date: '17-26',
      rating: '4.67'
    },
    {
      place: 'Lonavla,India',
      img1 : lonavala1,
      img2 : lonavala2,
      img3 : lonavala3,
      host : 'Tanya',
      price: '6,988',
      date: '21-26',
      rating: '4.75'
    },
    {
      place: 'Maldives',
      img1 : maldives1,
      img2 : maldives2,
      img3 : maldives3,
      host : 'Leo',
      price: '51,069',
      date: '1-6',
      rating: '5.0'
    },
    {
      place: 'Mandrem,India',
      img1 : mandrem1,
      img2 : mandrem2,
      img3 : mandrem3,
      host : 'Brenden',
      price: '5,000',
      date: '4-9',
      rating: '4.69'
    },
    {
      place: 'Marchula,India',
      img1 : marchula1,
      img2 : marchula2,
      img3 : marchula3,
      host : 'Kalyani',
      price: '1,888',
      date: '1-6',
      rating: '4.64'
    },
    {
      place: 'Morjim,India',
      img1 : morjim1,
      img2 : morjim2,
      img3 : morjim3,
      host : 'Anvar',
      price: '5,706',
      date: '4-9',
      rating: '4.74'
    },
    {
      place: 'Mumbai,India',
      img1 : mumbai1,
      img2 : mumbai2,
      img3 : mumbai3,
      host : 'Jyeshtha',
      price: '9,129',
      date: '11-16',
      rating: '5.0'
    },
    {
      place: 'Nagaon,India',
      img1 : nagaon1,
      img2 : nagaon2,
      img3 : nagaon3,
      host : 'Ashvin',
      price: '2,536',
      date: '7-12',
      rating: '5.0'
    },
    {
      place: 'Nainital,India',
      img1 : nainital1,
      img2 : nainital2,
      img3 : nainital3,
      host : 'Madhu',
      price: '4,560',
      date: '16-26',
      rating: '4.68'
    },
    {
      place: 'Ramnagar,India',
      img1 : ramnagar1,
      img2 : ramnagar2,
      img3 : ramnagar3,
      hoat : 'Uteliaa',
      price: '9,600',
      date: '4-6',
      rating: '4.70'
    },
    {
      place: 'Vagator,India',
      img1 : vagator1,
      img2 : vagator2,
      img3 : vagator3,
      host : 'Sidharth',
      price: '4,850',
      date: '5-16',
      rating: '4.9'
    }
  ]

export default rooms;